header component layout
larts85/masaje_las_manos pull request #13
Opened 2023-05-12 15:27 UTC by lucesitaliss

## State
Please delete options that are not relevant.
**READY/IN DEVELOPMENT/HOLD**

## Description

A few sentences describing the overall goals of the pull request's commits. Include relevant motivation and context. List any dependencies that are required for this change.

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2023-05-14 13:33 UTC, larts85 requested changes

2023-05-14 13:33 UTC, larts85 commented on public/images/languageMenu.svg
delete this image

2023-05-14 13:33 UTC, larts85 commented on public/images/languageButton.svg
delete this image

2023-05-14 13:33 UTC, larts85 commented on public/images/LogoPrimary.svg
the logo image must not have text

2023-05-14 13:33 UTC, larts85 commented on public/images/LogoSecondary.svg
the logo image must not have text

2023-05-14 13:33 UTC, larts85 commented on src/components/Header/index.tsx
> +          <li className={li}>{translations.navLinks.home}</li>
aca faltan cosillas

2023-05-14 13:50 UTC, larts85 approved these changes, later dismissed

2023-05-14 13:50 UTC, larts85 commented on src/styles/globals.ts
> +export const className = {}
I think we better reuse styles in Tailwind way:
https://tailwindcss.com/docs/reusing-styles#extracting-classes-with-apply

2023-05-24 13:23 UTC, lucesitaliss commented on src/components/Header/index.tsx
> +          <li className={li}>{translations.navLinks.home}</li>
este componente no es de esta rama

2023-07-13 22:27 UTC, larts85 requested changes

2023-07-13 22:27 UTC, larts85 commented on src/components/Header/headStyle.ts
> +const className = {
al nombre de este archivo le falta una s

2023-07-13 22:27 UTC, larts85 commented on src/components/Header/headStyle.ts
> +export const {
porque exportas todo separado?

2023-07-13 22:27 UTC, larts85 commented on src/components/Header/index.tsx
> +import {
luego acá tienes que importarlo todo separado

2023-07-13 22:27 UTC, larts85 commented on src/components/Header/index.tsx
> +  const [showMenu, setShowMenu] = useState(false)
`showMenu` sería el nombre de una función que muestra un menú, es decir no se corresponde el nombre de la variable con el tipo de dato del `useState`

2023-07-13 22:27 UTC, larts85 commented on src/components/Header/index.tsx
> +            <div className={showMenu ? 'rotate-180' : ''}>
este movimiento del icono debe estar animado

2023-07-13 22:27 UTC, larts85 commented on src/components/Header/index.tsx
> +        {/* languageBuuton [svg language text flecha]  menu*/}
typo

2023-07-13 22:27 UTC, larts85 commented on src/components/Header/index.tsx
> +            <div>
porque hay tantos svg dentro de este componente? Deben ser componentes independientes.

2023-07-13 22:27 UTC, larts85 commented on src/components/Header/index.tsx
> +        <nav className={nav}>
el navbar tambien debe ser un componente aparte

2023-07-13 22:27 UTC, larts85 commented on src/components/Header/index.tsx
> +            {showMenu && <LangButtons />}
cuando le pasas la prop mobile? que por cierto deberia ser `isMobile` en caso de ser un buleano

2023-07-14 14:22 UTC, lucesitaliss commented on src/components/Header/index.tsx
> +  const [showMenu, setShowMenu] = useState(false)
no entendí esto.

2023-07-14 14:24 UTC, lucesitaliss commented on src/components/Header/index.tsx
> +            <div className={showMenu ? 'rotate-180' : ''}>
ademas de que rote que otra animación le falta? no entiendo esto tampoco

2023-07-14 16:30 UTC, lucesitaliss commented on src/components/Header/index.tsx
> +            {showMenu && <LangButtons />}
cuando lo renderizo

2023-09-13 11:29 UTC, larts85 requested changes

2023-09-13 11:29 UTC, larts85 commented on package.json
> -    "@testing-library/jest-dom": "^5.16.5",
Sácale el caret `^` a todas las versiones de las dependencias. Hay un vídeo de midudev que habla sobre esto tengo que verlo

2023-09-13 11:29 UTC, larts85 commented on src/components/Button/buttons.styles.ts
> +    [VARIANT_STATES.NORMAL]: `w-175px h-52px cursor-auto text-secondary-base rounded-md  text-${typografyClassName.component.textButton} uppercase hover:shadow-button-hover active:shadow-button-prima
Saca todos los doble espacios

2023-09-13 11:29 UTC, larts85 commented on src/components/Header/headStyles.ts
> +const className = {
Ajusta el nombre del archivo para que quede uniforme

2023-09-13 11:29 UTC, larts85 commented on src/components/Header/index.tsx
> +          <div data-testid="logoImage" className={logoImage}>
Porque hay 3 div wrapeando un logo?

2023-09-13 16:04 UTC, lucesitaliss commented on src/components/Header/index.tsx
> +          <div data-testid="logoImage" className={logoImage}>
Hay un div contenedor del logo y del botón languageButton, y a su vez el logo puede se puede renderizar de dos maneras, cuando la pantalla es muy pequeña solo la imagen 
![image](https://github.com/larts85/masaje_las_manos/assets/86491656/3eec1320-3c4b-416e-8270-55a9c382f1e0)
y cuando es un poco mas grande imagen y texto
![image](https://github.com/larts85/masaje_las_manos/assets/86491656/69197ad9-4a6b-4152-aa1b-44dbf7f0adce)
 por tanto la estructura es:
<div contenedor de logo y button>
     <div contenedor de las variantes de logo>
         <div variante 1 de logo/>
         <div variante 2 de logo/>
    </div contenedor de las variantes de logo>
    <div del boton/>
</div contenedor de logo y button>

2023-09-14 08:54 UTC, larts85 requested changes

2023-09-14 08:54 UTC, larts85 commented on src/components/Button/buttons.styles.ts
> +import { className as typografyClassName } from '@/components/storyBook/Typography/Component'
Acá se usa ph en lugar de f

2023-09-14 08:54 UTC, larts85 commented on src/components/Header/index.tsx
> +        <div className="logo justify-start">
Avísame para ver en vivo esto de los div anidados, creo que se puede simplificar. Además no deberías tener la clase logo

2023-09-14 08:54 UTC, larts85 commented on src/components/ImagesComponents/MenuArrowNext.tsx
> +const MenuArrowNext = () => {
Yo creo que un solo icono de flecha es suficiente, y simplemente lo rotas con css según la situación. Los componentes SVG deberían recibir las props y destructurarlas en el elemento SVG tipo `{...props}`

2023-09-14 08:54 UTC, larts85 commented on src/components/ImagesComponents/MenuCheck.tsx
> +const MenuCheck = () => {
Aplicable lo de las props a todos los componentes SVG, eso te permite después pasarle propiedades como className u otras más específicas de estilos que soporta el SVG

2023-09-14 08:54 UTC, larts85 commented on src/components/ImagesComponents/imagesComponents.test.tsx
> +    expect(container).toBeTruthy()
Acá mejor usar `toBeInTheDocument()` capaz que incluso pasar alguna prop y luego checkear con `toHaveAttribute(...)`

2023-09-14 08:54 UTC, larts85 commented on src/components/LanguagesButton/index.test.tsx
> +// Mock useState globally
Eliminar comentarios

2023-09-14 08:54 UTC, larts85 commented on src/components/LanguagesButton/index.tsx
> +  return (
Falta salto de línea

2023-09-14 08:54 UTC, larts85 commented on src/components/LanguagesButton/index.tsx
> +  const handleClick = () => {
Mejorar el nombre de la función

2023-09-14 08:54 UTC, larts85 commented on src/components/LanguagesButton/index.tsx
> +            className={`mobileLanguageButton ${mobilelanguageButton}
Recuerda eliminar todas las clases truchas

2023-09-14 08:54 UTC, larts85 commented on src/components/LanguagesButton/index.tsx
> +          <div
Este es un ejemplo de anidado innecesario, el componente `<LanguageMenu/>` ya es de por si un elemento div, y acá lo estás wrapeando con otro, evita usar elementos de más, solo los que tengan sentido, e intenta usar elementos semánticos siempre que sea posible.

2023-09-14 08:54 UTC, larts85 commented on src/components/Logo/index.tsx
> +      light: '#88DBDF',
No encontraste las manera de importar la configuración de Tailwind acá para evitar los magic strings?

2023-09-14 08:54 UTC, larts85 commented on src/components/Logo/index.tsx
> +  const logoColor = () => {
Primero mejorar el nombre de la función, después el `else` es innecesario, incluso más simple podrías asignarle el valor a la variable con un ternario

2023-09-14 08:54 UTC, larts85 commented on src/components/Logo/index.tsx
>    const logoStyleVariants: StyleVariants = {
Mejorar este nombre

2023-09-14 08:54 UTC, larts85 commented on src/components/Logo/logo.types.ts
> +  text?: true | false
Acá en tipo sería boolean, eso es redundante

2023-09-14 08:54 UTC, larts85 commented on src/components/storyBook/Typography/Component.tsx
>    categoryDiv: 'bg-Primary-lighter w-72 rounded-lg mb-4',
El nombre de este archivo no debería ser **Component** sino **index**

2023-09-14 08:54 UTC, larts85 commented on src/pages/about/index.tsx
> +    <div>
Acá tendrías que fijarte como termina en el DOM el componente, pero este div creo podría ser un fragmento que tenga el `<Header />` y un `<main>`

2023-09-14 08:54 UTC, larts85 commented on src/pages/index.tsx
>        <Head>
Por lo que veo al resto de las páginas les falta el head

2023-09-14 08:54 UTC, larts85 commented on src/pages/services/index.tsx
> +    <div data-testid="services">
Siempre del mar específico, `data-testid="services-page"`

2023-09-14 08:54 UTC, larts85 commented on tailwind.config.js
> +      keyframes: {
Sacar si no se usa

2023-09-14 13:14 UTC, lucesitaliss commented on src/components/ImagesComponents/MenuArrowNext.tsx
> +const MenuArrowNext = () => {
No entiendo q me quieres decir con esto. Los componentes SVG deberían recibir las props y destructurarlas en el elemento SVG tipo {...props}

2023-09-14 13:51 UTC, lucesitaliss commented on src/components/storyBook/Typography/Component.tsx
>    categoryDiv: 'bg-Primary-lighter w-72 rounded-lg mb-4',
ya hay un Index, ese se llama component pq es el nombre q tiene una de las categorias de las tipografias
![image](https://github.com/larts85/masaje_las_manos/assets/86491656/44b06abe-94f8-40fa-aec1-09c0ba9666b2)

2023-09-18 19:38 UTC, larts85 approved these changes

2023-09-18 19:39 UTC, merged