Feature/configuration tailwinds styles
larts85/masaje_las_manos pull request #15
Opened 2023-05-23 17:51 UTC by lucesitaliss

## State
Please delete options that are not relevant.
**READY/IN DEVELOPMENT/HOLD**

## Description

A few sentences describing the overall goals of the pull request's commits. Include relevant motivation and context. List any dependencies that are required for this change.

## Type of change
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2023-05-23 17:54 UTC, lucesitaliss commented
![image](https://github.com/larts85/masaje_las_manos/assets/86491656/d5fcbe32-1acd-4507-ad0c-b0016f664269)
![image](https://github.com/larts85/masaje_las_manos/assets/86491656/5e7bbe1c-2bed-4153-9a09-4110e60c05d3)

2023-05-24 01:05 UTC, lucesitaliss commented
![image](https://github.com/larts85/masaje_las_manos/assets/86491656/8d2549e8-b295-46d1-ac1b-f38c5fb9c9eb)

2023-05-24 17:32 UTC, larts85 requested changes

2023-05-24 17:32 UTC, larts85 commented on src/components/storyBook/Button/index.tsx
> +  }
falta salto de linea

2023-05-24 17:32 UTC, larts85 commented on tailwind.config.js
> +        Primary: {
minusculas

2023-05-24 17:32 UTC, larts85 commented on tailwind.config.js
> +        variations: {
cambiar este nombre

2023-05-24 17:32 UTC, larts85 commented on tailwind.config.js
> +          transparentBorder: 'rgba(0, 0, 0, 0.7)',
unificar estilo de color `rgba` o `hex`

2023-05-24 17:32 UTC, larts85 commented on tailwind.config.js
> +    extend: {
creo que te faltan los `border-radius`

2023-05-24 17:32 UTC, larts85 commented on src/pages/storybook/index.tsx
> +      <Typografy />
aca tienes un typo no se usa f sino ph

2023-05-24 17:32 UTC, larts85 commented on src/pages/index.tsx
> +      <button className="btn-primary">Save changes</button>
aca tienes el ejemplo que ya esta en `/global.css`

2023-05-24 17:32 UTC, larts85 commented on src/pages/storybook/index.tsx
> +    </>
tienes que agregar los iconos también que vamos usando en el proyecto

2023-05-30 18:37 UTC, larts85 approved these changes

2023-05-30 18:37 UTC, larts85 commented on src/pages/story-book/index.tsx
> +const StoryBook: FC = () => {
NextPage

2023-05-30 18:37 UTC, larts85 commented on src/pages/story-book/index.tsx
> +    <>
seria el layout, y debe tener padding

2023-05-30 18:37 UTC, larts85 commented on src/components/Logo/image/neutralIcon.svg
eliminar archivo svg

2023-05-30 18:37 UTC, larts85 commented on src/components/Logo/image/primaryIcon.svg
eliminar archivo svg

2023-05-30 18:37 UTC, larts85 commented on src/components/Logo/image/secondaryIcon.svg
eliminar archivo svg

2023-05-30 18:37 UTC, larts85 commented on src/components/Logo/index.tsx
> +    [VARIANT.TRANSPARENT]: {
esto tienes que arreglarlo con los tipos no este hack

2023-05-30 18:37 UTC, larts85 commented on src/components/storyBook/Button/index.tsx
> +        <Button variant={VARIANT.PRIMARY} isDisable={false} />
agregar mas padding entre los botones

2023-05-30 18:37 UTC, larts85 commented on src/components/Logo/index.tsx
> +  const logoStyleVariants = {
esto no me gusta, no deberías tener colores hardcodeados, si se supone que son los que ya tenemos en nuestra paleta, tienes que reutilizar esas variables de alguna manera

2023-05-30 18:37 UTC, larts85 commented on src/components/Logo/index.tsx
> +      v4: '#068A8F',
ademas tienes 5 versiones  por cada variante cuando solo necesitas 3

2023-05-30 18:37 UTC, larts85 commented on src/components/RadioButtons/index.tsx
> +  [VARIANT.TRANSPARENT]: {},
yo juraría que esto lo arreglamos con el tipado, o te habia dicho como hacerlo, usando un `type` o `interface` en lugar de `enum`

2023-05-30 18:37 UTC, larts85 commented on src/components/RadioButtons/index.tsx
> +      'bg-primary-base w-4 h-4 rounded-full block absolute left-1 top-1',
no se que hiciste en el checked pero el centro te quedó descentrado

2023-05-30 18:37 UTC, larts85 commented on src/components/RadioButtons/index.tsx
> +      'appearance-none w-6 h-6 rounded-full border-2 border-nautral-base  cursor-pointer ',
en el not-checked te falta la lógica para pintar el relleno atenuado cuando se hace hover

2023-05-30 18:37 UTC, larts85 approved these changes

2023-05-30 18:40 UTC, larts85 requested changes

2023-05-30 18:40 UTC, larts85 commented on src/pages/story-book/index.tsx
> +    <>
le pusiste flex pero no padding, esta pegado al fondo, ahora no se ve tanto por falta de elementos

2023-05-30 18:40 UTC, larts85 commented on src/pages/story-book/index.tsx
> +        <div>
estos div son innecesarios, pero si lo fuesen deberían ir dentro del componente

2023-06-04 16:50 UTC, larts85 requested changes

2023-06-04 16:50 UTC, larts85 commented on src/components/Button/index.tsx
> +      {variant}
a este componente button le faltan props, ya lo hablamos,.
¿El texto que se mostrará será siempre la variante usada?
¿Que va a suceder cuando se le haga click?

2023-06-04 17:14 UTC, larts85 reviewed
Tienes que testear los nuevos componentes dentro de src/components.

2023-06-04 17:14 UTC, larts85 commented on src/components/Logo/index.tsx
> +      v1: '#88DBDF',
Investigar como traerse los conlores de la configuración de tailwind

2023-06-04 17:14 UTC, larts85 commented on src/components/RadioButtons/index.tsx
> +  }
falta salto de linea

2023-06-04 17:14 UTC, larts85 commented on src/components/RadioButtons/index.tsx
> +        <label key={option} className="relative  block">
doble espacio innecesario

2023-06-04 17:14 UTC, larts85 commented on src/components/RadioButtons/types.ts
> +export interface RadioButtonVariants {
esto no puede llamarse variants, porque son las props del componente, lo mismo en los otros componentes. Seria RadioButyonProps

2023-06-04 17:14 UTC, larts85 commented on src/components/RadioButtons/index.tsx
> +            name={option}
Acá estas asumiendo que las opciones son un arreglo de strings, cuando en la vida real es un caso raro, generalmente los arreglos son de objetos, asi que se debería acceder al la key name de cada posición.

2023-06-04 17:14 UTC, larts85 commented on src/components/RadioButtons/index.tsx
> +            checked={selectOption === option}
este checked creo que mejor cambiarlo por value, donde lo encontraste así? Ademas debe venir por props.

2023-06-04 17:14 UTC, larts85 commented on src/components/RadioButtons/index.tsx
> +  const handleOptionChange = (event: React.ChangeEvent<HTMLInputElement>) => {
Acá el handler debe venir por props, porque ademas de setearse el state que define el seleccionado (que podría ser un useState pero tambien venir de redux), se hacen otras cosas con la data seleccionada posiblemente. Entonces este componente se abstrae de eso.

2023-06-04 17:14 UTC, larts85 commented on src/components/storyBook/Button/index.tsx
> +    'w-400px h-89px border-2 border-dashed border-stone-500 gap-2 flex p-2 ml-5 mt-5 mb-5 justify-center items-center',
Investigar como poder usar los colores de la config de tailwind en el color del border.

2023-06-04 17:14 UTC, larts85 commented on src/components/storyBook/Logo/index.tsx
> +StoryBookLogo.displayName = 'StoryBookLogo'
Este displayName posibilita que en la devtool de react en ambientes productivos se vea el nombre del componente en lugar de una letra random.

2023-06-04 17:17 UTC, larts85 requested changes
revisar comments en pr y en la pagina, siempre fijate porque falla el pipeline.

2023-06-04 17:17 UTC, larts85 commented on src/styles/color palette.ts
> +export const colors = {
estoi porque?

2023-06-04 17:17 UTC, larts85 commented on tailwind.config.js
> +      borderWidth: {
agregar borderRadius

2023-06-06 14:47 UTC, lucesitaliss commented on src/components/RadioButtons/index.tsx
> +            checked={selectOption === option}
No entiendo q es lo que me estás pidiendo acá

2023-06-06 14:52 UTC, lucesitaliss commented on src/components/storyBook/Logo/index.tsx
> +StoryBookLogo.displayName = 'StoryBookLogo'
no entiendo esto.

2023-06-13 07:55 UTC, larts85 requested changes

2023-06-13 07:55 UTC, larts85 commented on src/components/Button/Index.test.tsx
> +    debug(button)
Eliminar debug

2023-06-13 07:55 UTC, larts85 commented on src/components/Button/Index.test.tsx
> +  it('should disable button when disable prop is', () => {
Falta salto de línea y terminar el título

2023-06-13 07:55 UTC, larts85 commented on src/components/Button/Index.test.tsx
> +    expect(button).toBeDisabled()
Separar con saltos de línea según tipo de lógica

2023-06-13 07:55 UTC, larts85 commented on src/components/Button/Index.test.tsx
> +import { render, fireEvent, screen } from '@testing-library/react'
Si el nombre del archivo index.tsx no está con mayúsculas, ¿porqué este lo estaría? Cambiarlo en todos lados!

2023-06-13 07:55 UTC, larts85 commented on src/components/Logo/index.tsx
> +      v4: '#333333',
Porque v4?

2023-06-13 07:55 UTC, larts85 commented on src/components/Logo/Index.test.tsx
> +    const pathElements = svgElement.getElementsByTagName('path')
Porque no puedes buscar desde el objeto `screen`?

2023-06-13 07:55 UTC, larts85 commented on src/components/RadioButtons/Index.test.tsx
> +    debug()
Delete

2023-06-13 07:55 UTC, larts85 commented on src/components/RadioButtons/index.tsx
> +            checked={selectOption === option.option}
Esto no lo cambiaste a `value`, además debería ser `option.name`

2023-06-13 07:55 UTC, larts85 commented on src/components/RadioButtons/radioButton.types.ts
> +export interface ClassName {
Este tipo ya existe en los globales. Siempre agrega saltos de línea

2023-06-13 07:55 UTC, larts85 commented on src/components/RadioButtons/index.tsx
> +  const handleOptionChange = (event: React.ChangeEvent<HTMLInputElement>) => {
Sin resolver

2023-06-13 07:55 UTC, larts85 commented on src/components/Button/index.tsx
> +  name,
Esto no debería llamarse name, sino texto o cta (calle yo action). Un botón también debería tener la capacidad de embeber un icono junto con el texto, ya sea a la derecha como a la izquierda. Fíjate en el proyecto ss-site

2023-06-13 07:55 UTC, larts85 commented on src/types/globals.types.ts
> +  NEUTRAL = ' neutral',
Espacio

2023-06-13 07:55 UTC, larts85 commented on tailwind.config.js
> +        '1px': '1px',
Este es el 3er comentario donde te pido los `border-radius`

2023-06-13 17:49 UTC, lucesitaliss commented on src/components/RadioButtons/radioButton.types.ts
> +export interface ClassName {
no se a que tipo te refieres

2023-06-13 18:57 UTC, lucesitaliss commented on src/components/Button/index.tsx
> +  name,
queda pendiente el icono por falta de diseño.

2023-06-13 19:00 UTC, lucesitaliss commented on tailwind.config.js
> +        '1px': '1px',
listo, ya lo hice. Perdón la demora

2023-06-13 21:46 UTC, larts85 requested changes
fijate bien los comments que te faltan por responder

2023-06-13 21:46 UTC, larts85 commented on tailwind.config.js
> +        '1px': '1px',
te faltaron 2 segun el diseño
![image](https://github.com/larts85/masaje_las_manos/assets/68341136/2cfdb942-7993-4e70-9f6f-cde1b8b0c23b)

2023-06-27 23:57 UTC, larts85 approved these changes

2023-06-27 23:58 UTC, merged